# Generated by Django 5.1.1 on 2024-11-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=255)),
                ('about', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
