# Generated by Django 5.1.1 on 2024-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_profile_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='website',
            field=models.URLField(default='www.gn.com', max_length=300),
            preserve_default=False,
        ),
    ]
