# Generated by Django 5.1.1 on 2024-11-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_certifications_certificate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default=1, upload_to='skill_logos/'),
            preserve_default=False,
        ),
    ]
