# Generated by Django 5.1.1 on 2024-11-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_alter_skill_logo_alter_sociallink_social_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='username_url',
            field=models.URLField(unique=True),
        ),
    ]
