# Generated by Django 5.1.1 on 2024-11-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_alter_skill_name_alter_sociallink_username_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
