# Generated by Django 5.1.1 on 2024-11-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_profile_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='intro',
            new_name='sub_heading',
        ),
    ]
