# Generated by Django 5.1.1 on 2024-11-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_rename_intro_profile_sub_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='social_logo',
            new_name='logo',
        ),
    ]
