# Generated by Django 5.1.1 on 2024-11-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0015_remove_sociallink_username_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='your_address',
        ),
    ]
