# Generated by Django 5.1.1 on 2024-11-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0016_remove_sociallink_your_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='your_address',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
