# Generated by Django 5.1.1 on 2024-11-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0017_sociallink_your_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='job_title',
            new_name='position',
        ),
    ]
