# Generated by Django 5.1.1 on 2024-11-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0019_jobtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='task',
            field=models.CharField(max_length=1000),
        ),
    ]
