# Generated by Django 5.1.1 on 2025-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0020_alter_jobtask_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('seen', models.BooleanField(default=False)),
                ('delivered_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
