# Generated by Django 5.1.1 on 2025-01-16 07:18

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0021_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_pic/', validators=[portfolio_app.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
