# Generated by Django 5.1.1 on 2025-01-16 07:30

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0022_profile_profile_picture_alter_inbox_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_mini',
            field=models.FileField(null=True, upload_to='profile_pic/', validators=[portfolio_app.models.validate_image_file]),
        ),
    ]
