# Generated by Django 5.1.1 on 2025-01-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0023_profile_profile_picture_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='website',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
