# Generated by Django 5.1.1 on 2025-01-19 08:39

import django.db.models.deletion
import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0024_alter_education_details_alter_education_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='imageSets/', validators=[portfolio_app.models.validate_image_file])),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='explored',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio_app.imagesets'),
        ),
    ]
