# Generated by Django 5.1.1 on 2025-01-19 08:45

import django.db.models.deletion
import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0025_imagesets_remove_project_explored_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='ProjectImage/', validators=[portfolio_app.models.validate_image_file])),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio_app.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageSets',
        ),
    ]
