# Generated by Django 5.1.1 on 2025-01-19 09:13

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0026_remove_project_images_projectimage_delete_imagesets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='img',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_list',
            field=models.ImageField(blank=True, null=True, upload_to='ProjectImage/', validators=[portfolio_app.models.validate_image_file]),
        ),
    ]
