# Generated by Django 5.1.5 on 2025-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0027_remove_projectimage_img_projectimage_image_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='problem_statement',
            new_name='problem_of_statement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='solution_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
