# Generated by Django 5.1.5 on 2025-04-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0028_rename_problem_statement_project_problem_of_statement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inbox',
            unique_together={('sender_email', 'message')},
        ),
    ]
