# Generated by Django 5.1.5 on 2025-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0029_alter_inbox_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="projects", to="portfolio_app.tag"
            ),
        ),
    ]
