# Generated by Django 5.1.5 on 2025-05-02 13:26

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0030_alter_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="projects", to="portfolio_app.tag"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="logo",
            field=models.FileField(
                blank=True,
                default="skill_default.svg",
                upload_to="skill_logos/",
                validators=[portfolio_app.models.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="skills", to="portfolio_app.tag"
            ),
        ),
    ]
