# Generated by Django 5.1.5 on 2025-05-02 13:28

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0031_alter_project_tags_alter_skill_logo_alter_skill_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="logo",
            field=models.FileField(
                default="skill_default.svg",
                upload_to="skill_logos/",
                validators=[portfolio_app.models.validate_image_file],
            ),
        ),
    ]
