# Generated by Django 5.1.5 on 2025-05-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0034_alter_projectimage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
