# Generated by Django 5.1.5 on 2025-05-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0037_alter_skill_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="feature",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="portfolio_app.project",
            ),
        ),
    ]
