# Generated by Django 5.1.5 on 2025-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0039_resume_alter_project_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(
                blank=True,
                help_text="optional, if a github link is available for this project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="optional, if a link is available for this project",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="video_link",
            field=models.URLField(
                blank=True,
                help_text="optional, if a video is available for this project",
                null=True,
            ),
        ),
    ]
