# Generated by Django 5.1.5 on 2025-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0041_project_category_project_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.IntegerField(
                default=1000,
                help_text="Use this to sort projects in the list, lower number means  top of the list",
            ),
        ),
    ]
