# Generated by Django 5.1.5 on 2025-08-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0042_project_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order"]},
        ),
    ]
