# Generated by Django 5.1.5 on 2025-08-12 12:17

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0043_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="logo",
            field=models.FileField(
                blank=True,
                default="skill_logos/skill_default.svg",
                upload_to="skill_logos/",
                validators=[portfolio_app.models.validate_image_file],
            ),
        ),
    ]
