# Generated by Django 5.1.5 on 2025-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="International",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date_posted", models.CharField(max_length=100)),
                ("employment_type", models.CharField(max_length=100)),
                ("experience_level", models.CharField(max_length=100)),
                ("salary", models.CharField(max_length=100)),
                ("deadline", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date_posted", models.CharField(max_length=100)),
                ("employment_type", models.CharField(max_length=100)),
                ("experience_level", models.CharField(max_length=100)),
                ("salary", models.CharField(max_length=100)),
                ("deadline", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
