# Generated by Django 5.1.5 on 2025-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scrap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="international",
            name="date_posted",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="international",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="local",
            name="date_posted",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="local",
            name="deadline",
            field=models.DateField(),
        ),
    ]
