# Generated by Django 5.1.5 on 2025-08-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scrap", "0002_alter_international_date_posted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="international",
            name="action",
            field=models.CharField(
                choices=[("applied", "Applied"), ("not_interested", "Not Interested")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="local",
            name="action",
            field=models.CharField(
                choices=[("applied", "Applied"), ("not_interested", "Not Interested")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
